/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CounselingRouteImport } from './routes/counseling'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as CollegePredictorRouteImport } from './routes/college-predictor'
import { Route as ClaimCollegeRouteImport } from './routes/claim-college'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as DashboardCollegeRouteImport } from './routes/dashboard.college'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CollegesSlugRouteImport } from './routes/colleges.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselingRoute = CounselingRouteImport.update({
  id: '/counseling',
  path: '/counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegePredictorRoute = CollegePredictorRouteImport.update({
  id: '/college-predictor',
  path: '/college-predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCollegeRoute = ClaimCollegeRouteImport.update({
  id: '/claim-college',
  path: '/claim-college',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamsRoute,
} as any)
const DashboardCollegeRoute = DashboardCollegeRouteImport.update({
  id: '/dashboard/college',
  path: '/dashboard/college',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CollegesSlugRoute = CollegesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollegesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/claim-college': typeof ClaimCollegeRoute
  '/college-predictor': typeof CollegePredictorRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/counseling': typeof CounselingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/college': typeof DashboardCollegeRoute
  '/exams/$slug': typeof ExamsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/claim-college': typeof ClaimCollegeRoute
  '/college-predictor': typeof CollegePredictorRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/counseling': typeof CounselingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/college': typeof DashboardCollegeRoute
  '/exams/$slug': typeof ExamsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/claim-college': typeof ClaimCollegeRoute
  '/college-predictor': typeof CollegePredictorRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/counseling': typeof CounselingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/college': typeof DashboardCollegeRoute
  '/exams/$slug': typeof ExamsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/claim-college'
    | '/college-predictor'
    | '/colleges'
    | '/compare'
    | '/counseling'
    | '/courses'
    | '/exams'
    | '/questions'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/dashboard/college'
    | '/exams/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/claim-college'
    | '/college-predictor'
    | '/colleges'
    | '/compare'
    | '/counseling'
    | '/courses'
    | '/exams'
    | '/questions'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/dashboard/college'
    | '/exams/$slug'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/claim-college'
    | '/college-predictor'
    | '/colleges'
    | '/compare'
    | '/counseling'
    | '/courses'
    | '/exams'
    | '/questions'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/articles/$slug'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/dashboard/college'
    | '/exams/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ClaimCollegeRoute: typeof ClaimCollegeRoute
  CollegePredictorRoute: typeof CollegePredictorRoute
  CollegesRoute: typeof CollegesRouteWithChildren
  CompareRoute: typeof CompareRoute
  CounselingRoute: typeof CounselingRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ExamsRoute: typeof ExamsRouteWithChildren
  QuestionsRoute: typeof QuestionsRoute
  ReviewsRoute: typeof ReviewsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DashboardCollegeRoute: typeof DashboardCollegeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counseling': {
      id: '/counseling'
      path: '/counseling'
      fullPath: '/counseling'
      preLoaderRoute: typeof CounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-predictor': {
      id: '/college-predictor'
      path: '/college-predictor'
      fullPath: '/college-predictor'
      preLoaderRoute: typeof CollegePredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-college': {
      id: '/claim-college'
      path: '/claim-college'
      fullPath: '/claim-college'
      preLoaderRoute: typeof ClaimCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/dashboard/college': {
      id: '/dashboard/college'
      path: '/dashboard/college'
      fullPath: '/dashboard/college'
      preLoaderRoute: typeof DashboardCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/colleges/$slug': {
      id: '/colleges/$slug'
      path: '/$slug'
      fullPath: '/colleges/$slug'
      preLoaderRoute: typeof CollegesSlugRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface CollegesRouteChildren {
  CollegesSlugRoute: typeof CollegesSlugRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesSlugRoute: CollegesSlugRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ExamsRouteChildren {
  ExamsSlugRoute: typeof ExamsSlugRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsSlugRoute: ExamsSlugRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ClaimCollegeRoute: ClaimCollegeRoute,
  CollegePredictorRoute: CollegePredictorRoute,
  CollegesRoute: CollegesRouteWithChildren,
  CompareRoute: CompareRoute,
  CounselingRoute: CounselingRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ExamsRoute: ExamsRouteWithChildren,
  QuestionsRoute: QuestionsRoute,
  ReviewsRoute: ReviewsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DashboardCollegeRoute: DashboardCollegeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
