/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as ExamPrepRouteImport } from './routes/exam-prep'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CounselingRouteImport } from './routes/counseling'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as CollegePredictorRouteImport } from './routes/college-predictor'
import { Route as ClaimCollegeRouteImport } from './routes/claim-college'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyAbroadSlugRouteImport } from './routes/study-abroad.$slug'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as ExamPrepSlugRouteImport } from './routes/exam-prep.$slug'
import { Route as DashboardCollegeRouteImport } from './routes/dashboard.college'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CollegesSlugRouteImport } from './routes/colleges.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamPrepRoute = ExamPrepRouteImport.update({
  id: '/exam-prep',
  path: '/exam-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselingRoute = CounselingRouteImport.update({
  id: '/counseling',
  path: '/counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegePredictorRoute = CollegePredictorRouteImport.update({
  id: '/college-predictor',
  path: '/college-predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimCollegeRoute = ClaimCollegeRouteImport.update({
  id: '/claim-college',
  path: '/claim-college',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadSlugRoute = StudyAbroadSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudyAbroadRoute,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamsRoute,
} as any)
const ExamPrepSlugRoute = ExamPrepSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExamPrepRoute,
} as any)
const DashboardCollegeRoute = DashboardCollegeRouteImport.update({
  id: '/dashboard/college',
  path: '/dashboard/college',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CollegesSlugRoute = CollegesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollegesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/claim-college': typeof ClaimCollegeRoute
  '/college-predictor': typeof CollegePredictorRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/counseling': typeof CounselingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/exam-prep': typeof ExamPrepRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/college': typeof DashboardCollegeRoute
  '/exam-prep/$slug': typeof ExamPrepSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/claim-college': typeof ClaimCollegeRoute
  '/college-predictor': typeof CollegePredictorRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/counseling': typeof CounselingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/exam-prep': typeof ExamPrepRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/college': typeof DashboardCollegeRoute
  '/exam-prep/$slug': typeof ExamPrepSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/claim-college': typeof ClaimCollegeRoute
  '/college-predictor': typeof CollegePredictorRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/counseling': typeof CounselingRoute
  '/courses': typeof CoursesRouteWithChildren
  '/exam-prep': typeof ExamPrepRouteWithChildren
  '/exams': typeof ExamsRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/reviews': typeof ReviewsRoute
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/college': typeof DashboardCollegeRoute
  '/exam-prep/$slug': typeof ExamPrepSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles'
    | '/claim-college'
    | '/college-predictor'
    | '/colleges'
    | '/compare'
    | '/counseling'
    | '/courses'
    | '/exam-prep'
    | '/exams'
    | '/join'
    | '/login'
    | '/news'
    | '/questions'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/articles/$slug'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/dashboard/college'
    | '/exam-prep/$slug'
    | '/exams/$slug'
    | '/news/$slug'
    | '/scholarships/$slug'
    | '/study-abroad/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/claim-college'
    | '/college-predictor'
    | '/colleges'
    | '/compare'
    | '/counseling'
    | '/courses'
    | '/exam-prep'
    | '/exams'
    | '/join'
    | '/login'
    | '/news'
    | '/questions'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/articles/$slug'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/dashboard/college'
    | '/exam-prep/$slug'
    | '/exams/$slug'
    | '/news/$slug'
    | '/scholarships/$slug'
    | '/study-abroad/$slug'
  id:
    | '__root__'
    | '/'
    | '/articles'
    | '/claim-college'
    | '/college-predictor'
    | '/colleges'
    | '/compare'
    | '/counseling'
    | '/courses'
    | '/exam-prep'
    | '/exams'
    | '/join'
    | '/login'
    | '/news'
    | '/questions'
    | '/reviews'
    | '/scholarships'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/articles/$slug'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/dashboard/college'
    | '/exam-prep/$slug'
    | '/exams/$slug'
    | '/news/$slug'
    | '/scholarships/$slug'
    | '/study-abroad/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ClaimCollegeRoute: typeof ClaimCollegeRoute
  CollegePredictorRoute: typeof CollegePredictorRoute
  CollegesRoute: typeof CollegesRouteWithChildren
  CompareRoute: typeof CompareRoute
  CounselingRoute: typeof CounselingRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ExamPrepRoute: typeof ExamPrepRouteWithChildren
  ExamsRoute: typeof ExamsRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  QuestionsRoute: typeof QuestionsRoute
  ReviewsRoute: typeof ReviewsRoute
  ScholarshipsRoute: typeof ScholarshipsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyAbroadRoute: typeof StudyAbroadRouteWithChildren
  DashboardCollegeRoute: typeof DashboardCollegeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-prep': {
      id: '/exam-prep'
      path: '/exam-prep'
      fullPath: '/exam-prep'
      preLoaderRoute: typeof ExamPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counseling': {
      id: '/counseling'
      path: '/counseling'
      fullPath: '/counseling'
      preLoaderRoute: typeof CounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-predictor': {
      id: '/college-predictor'
      path: '/college-predictor'
      fullPath: '/college-predictor'
      preLoaderRoute: typeof CollegePredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-college': {
      id: '/claim-college'
      path: '/claim-college'
      fullPath: '/claim-college'
      preLoaderRoute: typeof ClaimCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/$slug': {
      id: '/study-abroad/$slug'
      path: '/$slug'
      fullPath: '/study-abroad/$slug'
      preLoaderRoute: typeof StudyAbroadSlugRouteImport
      parentRoute: typeof StudyAbroadRoute
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/exam-prep/$slug': {
      id: '/exam-prep/$slug'
      path: '/$slug'
      fullPath: '/exam-prep/$slug'
      preLoaderRoute: typeof ExamPrepSlugRouteImport
      parentRoute: typeof ExamPrepRoute
    }
    '/dashboard/college': {
      id: '/dashboard/college'
      path: '/dashboard/college'
      fullPath: '/dashboard/college'
      preLoaderRoute: typeof DashboardCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/colleges/$slug': {
      id: '/colleges/$slug'
      path: '/$slug'
      fullPath: '/colleges/$slug'
      preLoaderRoute: typeof CollegesSlugRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface CollegesRouteChildren {
  CollegesSlugRoute: typeof CollegesSlugRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesSlugRoute: CollegesSlugRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ExamPrepRouteChildren {
  ExamPrepSlugRoute: typeof ExamPrepSlugRoute
}

const ExamPrepRouteChildren: ExamPrepRouteChildren = {
  ExamPrepSlugRoute: ExamPrepSlugRoute,
}

const ExamPrepRouteWithChildren = ExamPrepRoute._addFileChildren(
  ExamPrepRouteChildren,
)

interface ExamsRouteChildren {
  ExamsSlugRoute: typeof ExamsSlugRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsSlugRoute: ExamsSlugRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ScholarshipsRouteChildren {
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
}

const ScholarshipsRouteChildren: ScholarshipsRouteChildren = {
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
}

const ScholarshipsRouteWithChildren = ScholarshipsRoute._addFileChildren(
  ScholarshipsRouteChildren,
)

interface StudyAbroadRouteChildren {
  StudyAbroadSlugRoute: typeof StudyAbroadSlugRoute
}

const StudyAbroadRouteChildren: StudyAbroadRouteChildren = {
  StudyAbroadSlugRoute: StudyAbroadSlugRoute,
}

const StudyAbroadRouteWithChildren = StudyAbroadRoute._addFileChildren(
  StudyAbroadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ClaimCollegeRoute: ClaimCollegeRoute,
  CollegePredictorRoute: CollegePredictorRoute,
  CollegesRoute: CollegesRouteWithChildren,
  CompareRoute: CompareRoute,
  CounselingRoute: CounselingRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ExamPrepRoute: ExamPrepRouteWithChildren,
  ExamsRoute: ExamsRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  QuestionsRoute: QuestionsRoute,
  ReviewsRoute: ReviewsRoute,
  ScholarshipsRoute: ScholarshipsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyAbroadRoute: StudyAbroadRouteWithChildren,
  DashboardCollegeRoute: DashboardCollegeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
